#ddev-generated
services:
  typesense:
    container_name: ddev-${DDEV_SITENAME}-typesense
    hostname: ${DDEV_SITENAME}-typesense
    image: typesense/typesense:0.25.1
    command: '--data-dir /data --api-key=test --enable-cors'
    networks: [default, ddev_default]
    restart: "no"
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
    ports:
      - "8108:8108"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
    - "typesense:/data"
    - ".:/mnt/ddev_config"
  typesense_admin:
    container_name: typesense_admin
    image: ghcr.io/lewynation/typesense-admin-dashboard:latest
    restart: always
    ports:
      - "3005:3000"
    external_links:
      - "ddev-router:${DDEV_SITENAME}.${DDEV_TLD}"
volumes:
  # typesense is a persistent Docker volume for typesense data
  # The persistent volume should have the same name as the service so it can be deleted
  # when the project is deleted.
  typesense: